baseURL = "https://i2y.github.io/romancy/"
title = "Romancy"
languageCode = "en"
defaultContentLanguage = "en"

# Hugo modules
[module]
[[module.imports]]
path = "github.com/imfing/hextra"

# Site parameters
[params]
description = "Lightweight durable execution framework for Go"

[params.navbar]
displayTitle = true
displayLogo = false

[params.page]
width = "wide"

[params.footer]
displayCopyright = true
displayPoweredBy = false

[params.editURL]
enable = true
base = "https://github.com/i2y/romancy/edit/main/website/content"

# Main menu
[[menu.main]]
name = "Documentation"
pageRef = "/docs"
weight = 1

[[menu.main]]
name = "GitHub"
url = "https://github.com/i2y/romancy"
weight = 2

# Sidebar menu
[[menu.sidebar]]
identifier = "getting-started"
name = "Getting Started"
pageRef = "/docs/getting-started"
weight = 1

[[menu.sidebar]]
identifier = "core-features"
name = "Core Features"
pageRef = "/docs/core-features"
weight = 2

[[menu.sidebar]]
identifier = "examples"
name = "Examples"
pageRef = "/docs/examples"
weight = 3

[[menu.sidebar]]
identifier = "integrations"
name = "Integrations"
pageRef = "/docs/integrations"
weight = 4

# Markup settings
[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
